### ISSUE TITLE
tocbot is not defined when trying to run storybook 6 locally

### ISSUE THREAD

**Issue by nik72619c** [tscanlin/tocbot#354]
Hi,
I am trying to use `storybook-docs-toc` package to show table of contents inside all of my mdx files in storybook but I keep on seeing this error which prevents my docs from opening.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'init')
    at TableOfContents.js:81:1
    at commitHookEffectListMount (react-dom.development.js:19731:1)
    at commitPassiveHookEffects (react-dom.development.js:19769:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at flushPassiveEffectsImpl (react-dom.development.js:22853:1)
    at unstable_runWithPriority (scheduler.development.js:653:1)
    at runWithPriority$1 (react-dom.development.js:11039:1)
    at flushPassiveEffects (react-dom.development.js:22820:1)
```

Here's what chrome devtools highlight
<img width="858" alt="Screenshot 2024-09-03 at 2 54 44 AM" src="https://github.com/user-attachments/assets/e955b072-0d4d-4d0c-b4de-75f054354541">

**Versions**
1. Storybook: 6.5.3
2. storybook-docs-toc: 1.7.0

Please let me know if there is any better place to share this error. I saw that the repository is archived as well.
Thanks in advance!

**Comment by nik72619c** [comment]
cc: @tscanlin

**Comment by tscanlin** [comment]
Hmm, that is strange. Can you tell me what version of tocbot is downloaded in node_modules? That may help me diagnose the issue.

**Comment by tscanlin** [comment]
Could you update to the latest version and see if that fixes it?
`npm install --save tocbot@4.29.0`

**Comment by nik72619c** [comment]
Tried this. Getting the same error

**Comment by tscanlin** [comment]
Closing due to no response / inactivity. But please re-open if you can respond to the questions above.
